plugins {
    id 'com.android.application'
}

android {
    namespace 'com.carstream.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.carstream.app'
        minSdk 29
        targetSdk 29
        versionCode 25
        versionName '1.5.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}

dependencies {
}
