const {parseHTML}=require('linkedom');
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const path=require('path');const root=path.resolve(__dirname,'../app/src/main/assets/client')+'/';
const {window}=parseHTML(fs.readFileSync(root+'index.html','utf8'));
const {document}=window;
const nativeTimeout=setTimeout;
const data=new Map(),requests=[],checks=[],errors=[];let mode='FREE';
const timers=new Map();let timerId=0;
window.setTimeout=(fn,ms)=>{const id=++timerId;if(ms<50)nativeTimeout(fn,0);else timers.set(id,{fn,ms});return id;};
window.clearTimeout=id=>timers.delete(id);window.setInterval=()=>0;
window.localStorage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};
window.location={hash:'#code=1234',pathname:'/',search:''};
window.history={replaceState(){window.location.hash=''}};

window.confirm=()=>{throw Error('Unexpected confirm')};window.prompt=()=>{throw Error('Unexpected prompt')};
window.console=console;window.Promise=Promise;
document.documentElement.requestFullscreen=()=>Promise.resolve();
for(const e of document.querySelectorAll('input'))e.value='';
const video=document.querySelector('video');
video.paused=true;video.currentTime=0;video.duration=70;video.readyState=0;video.videoWidth=0;
video.pause=function(){if(!this.paused){this.paused=true;this.dispatchEvent(new window.Event('pause'));}};
video.play=function(){this.paused=false;this.dispatchEvent(new window.Event('playing'));return Promise.resolve();};
video.load=function(){this.readyState=0;this.currentTime=0;if(this.src)nativeTimeout(()=>{this.readyState=4;this.videoWidth=640;this.dispatchEvent(new window.Event('loadedmetadata'));},0);};
const items=[];
for(let i=1;i<=25;i++)items.push({id:`22:${i}`,torrentId:22,fileId:i,title:`Elena.of.Avalor.S01E${String(i).padStart(2,'0')}.Test.Episode.${i}.1080p.mp4`,relativePath:`completed/Elena of Avalor/Season 1/Elena.S01E${String(i).padStart(2,'0')}.mp4`,sourceName:'Elena of Avalor Complete 1080p',size:1000000,ready:i<25});
items.push({id:'31:1',torrentId:31,fileId:1,title:'Another Show.mp4',relativePath:'Another Show.mp4',sourceName:'Another Show',ready:true});
window.fetch=async(url,opts)=>{
 const u=new URL(url,'http://test');assert.strictEqual(opts.headers['X-CarStream-Code'],'1234');let d={ok:true};
 if(u.pathname==='/api/library')d={items};
 if(u.pathname==='/api/state')d={commandVersion:0,controlMode:mode};
 if(u.pathname==='/api/playback'){requests.push(Object.fromEntries(u.searchParams));d={state:'READY',mode:'direct',durationSeconds:70,seekSeconds:Number(u.searchParams.get('startAt')),offsetSeconds:0,message:'Ready'};}
 if(u.pathname==='/api/skip-markers')d={segments:[],settings:{},nextMedia:null};
 return {ok:true,status:200,json:async()=>d};
};
const click=selector=>{const e=document.querySelector(selector);assert(e,selector);assert(!e.disabled,selector+' is disabled');e.click();};
const settle=()=>new Promise(r=>nativeTimeout(r,30));
const emit=name=>video.dispatchEvent(new window.Event(name));
(async()=>{
 vm.runInContext(fs.readFileSync(root+'app.js','utf8'),vm.createContext(window));
 assert.strictEqual(document.querySelector('#codeInput').value,'1234');assert.strictEqual(window.location.hash,'');
 click('#setupButton');await settle();
 assert.strictEqual(document.querySelector('#connection').textContent,'online');
 assert(data.get('carstreamClientName').startsWith('Screen '));
 checks.push('QR fragment prefills pairing code, clears URL, and optional name connects with auth headers');
 assert(!document.body.classList.contains('watching'));
 assert(document.querySelector('.folder-card').textContent.includes('Elena'));
 click('.folder-card');
 assert.strictEqual(document.querySelectorAll('.media-card').length,25);
 assert(document.querySelectorAll('.media-card')[1].textContent.includes('E02'));
 assert(document.querySelectorAll('.media-card')[9].textContent.includes('E10'));
 assert(document.querySelectorAll('.media-card')[24].disabled);
 assert(!document.querySelector('#folderPath').textContent.includes('completed'));
 checks.push('Browse-first view, Elena first when present, wrapper skipping, 25 cards, numeric order, unready episode disabled');
 click('#playFolderButton');await settle();
 assert(document.body.classList.contains('watching'));assert.strictEqual(requests.at(-1).mediaId,'22:1');assert(!video.paused);
 checks.push('Play from first episode selects episode 1 and opens watch view');
 video.currentTime=20;emit('timeupdate');click('#watchLibraryButton');
 assert(video.paused);assert(!document.body.classList.contains('watching'));assert(!document.querySelector('#returnVideoButton').classList.contains('hidden'));
 click('#returnVideoButton');await settle();assert(!video.paused);assert(document.body.classList.contains('watching'));
 checks.push('Episodes pauses; Back to video returns and resumes');
 click('#watchLibraryButton');click('.media-card');await settle();
 assert.strictEqual(requests.at(-1).startAt,'20');assert.strictEqual(video.currentTime,20);
 checks.push('Resume uses saved time without confirmation; loading does not overwrite progress');
 click('#startOverButton');await settle();assert.strictEqual(requests.at(-1).startAt,'0');assert.strictEqual(video.currentTime,0);
 checks.push('Start over requests time zero');
 video.currentTime=70;emit('ended');await settle();assert.strictEqual(requests.at(-1).mediaId,'22:2');
 checks.push('Ended event advances to next numbered episode');
 click('#overlayNextButton');await settle();assert.strictEqual(requests.at(-1).mediaId,'22:3');
 click('#autoNextButton');video.currentTime=70;const before=requests.length;emit('ended');await settle();assert.strictEqual(requests.length,before);assert(document.querySelector('#playerHint').textContent.includes('Tap Next'));
 click('#autoNextButton');
 checks.push('Manual Next advances; disabling Auto next prevents advancement and gives accurate finished text');
 click('#watchLibraryButton');document.querySelectorAll('.media-card')[23].click();await settle();assert(document.querySelector('#overlayNextButton').disabled);
 video.currentTime=70;emit('ended');await settle();assert.strictEqual(requests.at(-1).mediaId,'22:24');
 checks.push('Final ready episode stops rather than playing an unready video or another show');
 click('#watchLibraryButton');click('#folderRootButton');const search=document.querySelector('#search');search.value='S01E10';search.dispatchEvent(new window.Event('input'));assert.strictEqual(document.querySelectorAll('.media-card').length,1);
 checks.push('Search finds specific episode');
 mode='LOCKED';for(const [id,t]of timers){if(t.ms===1000){timers.delete(id);t.fn();break;}}await settle();
 assert(document.querySelector('#viewerShell').classList.contains('player-only'));assert(document.querySelector('#watchLibraryButton').classList.contains('hidden'));assert(document.querySelector('#overlayNextButton').disabled);
 checks.push('Parent lock keeps browsing hidden and episode changing disabled');
 fs.writeFileSync(path.join(__dirname,'logic-results.json'),JSON.stringify({kind:'DOM integration with simulated media and API; no rendering or decoding',checks,playbackRequests:requests.length},null,2));
 console.log(JSON.stringify({checks,playbackRequests:requests.length},null,2));
})().catch(e=>{console.error(e);process.exitCode=1});
